---
title       : Developing Data Products Course Project
subtitle    : 
author      : Gurraj Sangha
job         : 
framework   : io2012       # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
revealjs:
  theme: simple
knit        : slidify::knit2slides
---






## Developing Data Products
#  Course Project

#   Select cars that meet your specifications.

---

## INTRODUCTION
This presentation is part of the Course Project for the Coursera Developing Data Products class.  The project requires the development and deployment of a Shiny app.  The development occurred in RStudio and it was deployed on RStudio's servers.  Further, Slidify was used to prepare a reproducible pitch presentation about the application. 

The app developed for the first part of the assignment is avalilable at:

https://gsangha.shinyapps.io/Cars/


Source code for ui.R and server.R files are available on the GitHub:

https://github.com/gurraj/DevelopingDataProducts

---


## SELECT A CAR BASED ON YOUR SPECIFICATIONS
This app permits you to choose some cars based on the characteristics you desire.  The choice of features includes displacement, number of cylinders, transmission type, and horsepower.

---

## MTCARS DATASET
The data used in the app comes from the Motor Trend Car Road Tests (mtcars) dataset. The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973-74 models). We can look to some carachteristics of the data:


```
##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1
```
---



